### ISSUE TITLE
Refresh Webmention

### ISSUE THREAD

**Issue by dshanske** [pfefferle/wordpress-semantic-linkbacks#104]
What do you think of a way to, in the admin, refresh a webmention or webmentions?

https://make.wordpress.org/core/2016/10/04/custom-bulk-actions/

Thinking of using this...

**Comment by pfefferle** [comment]
is this really needed... if webmentions are implemented properly, they will send an update if something changes.

**Comment by dshanske** [comment]
This is mostly for refreshing old mentions that may not have been enhanced, for example if the plugin wasn't installed yet.
