### ISSUE TITLE
option to disable facepile just for mentions

### ISSUE THREAD

**Issue by snarfed** [pfefferle/wordpress-semantic-linkbacks#114]
i like the current logic for mentions that shows them when they're short enough. i'd like to keep that even with facepiles, by exempting either all mentions or short mentions below the threshold. example: https://snarfed.org/podcasts#comment-744582

**Comment by pfefferle** [comment]
this is not that easy because we are filtering by comment type... except we remove the „webmention“ comment type for these mentions...
