### ISSUE TITLE
handle non-square profile photos

### ISSUE THREAD

**Issue by snarfed** [pfefferle/wordpress-semantic-linkbacks#115]
the current markup for profile photos sets explicitly equal `width` and `height`, which squishes non-square profile photos. obviously not ideal. i'm guessing there's some alternative HTML + CSS to automatically center-crop, like silos do?

(looks like my theme also has CSS that sets explictly equal `width` and `height`, but that's probably on me to figure out.)

example: https://snarfed.org/2017-09-12_25492#li-comment-2608143 , with a 200x133 profile photo from facebook:

<img width="270" alt="image" src="https://user-images.githubusercontent.com/778068/31403423-e741bf6e-adad-11e7-8e5a-b91edd480457.png">

markup:

```html
<img alt="" src="https://graph.facebook.com/v2.10/10154059832022796/picture?type=large"
  srcset="https://graph.facebook.com/v2.10/10154059832022796/picture?type=large 2x"
  class="avatar avatar-48 photo avatar-default u-photo avatar-semantic-linkbacks" scale="0"
  height="48" width="48">
```

**Comment by snarfed** [comment]
good related discussion here, including one solution that's pure CSS but doesn't center. i expect that's possible though. https://stackoverflow.com/questions/16310918/css-scale-and-square-center-crop-image

**Comment by alohastone** [comment]
To me, using object-fit: cover for the .avatar class seems to be the easiest, CSS-only option. It keeps the aspect ratio and crops the image nicely: https://css-tricks.com/almanac/properties/o/object-fit/

![image](https://user-images.githubusercontent.com/3405023/31574236-88d83d42-b0cb-11e7-8421-cd40f386ef6c.png)

Doesn't work in IE, though. The article mentioned above has some workarounds for IE in the comment section.

**Comment by snarfed** [comment]
@alohastone awesome, thank you! `object-fit:cover` is perfect!

and yeah, lack of support in IE, edge, and older android (totally ~6% market share, https://caniuse.com/#feat=object-fit ) is disappointing, but looks like it degrades gracefully to the current behavior, so i expect we're fine with that.

sending a PR now!
