### ISSUE TITLE
Absence of `mbstring` php extensions causes webmentions to fail

### ISSUE THREAD

**Issue by miklb** [pfefferle/wordpress-semantic-linkbacks#122]
As reported in [indieweb-wordpress](https://chat.indieweb.org/wordpress/2017-11-11/1510423232495000) the inclusion of the `mb_convert_encoding` can cause a fatal error if the `mbstring` php extension is not active or installed.

Report said that webmentions were not received with semantic linkbacks active, deactivating it allowed them to be received, thus why I opened it in the issue in this plugin.

When I looked for other examples of that function in core WordPress it seems `if ( function_exists('mb_convert_encoding') )` is used.

@dshanske said it is a result of the php mf2 library so not sure if we need to do a PR upstream to wrap those in an if statement or do something on plugin side.

Just wanted to document so we don't forget to address.

**Comment by dshanske** [comment]
The thing is, the file in question is the PHP-MF2 Parser.

**Comment by dshanske** [comment]
At the least, let's consider raising a flag if this happens.
