### ISSUE TITLE
Expanding beyond 8 photos in facepiles only works for likes

### ISSUE THREAD

**Issue by chrisaldrich** [pfefferle/wordpress-semantic-linkbacks#125]
I'm finding that after updating to v3.6.0, when clicking on the ellipses for any of the sections for likes, reposts, or mentions the only section that is expanded is the likes section regardless of which set of ellipses is clicked. It doesn't seem to be possible to expand the reposts or mentions sections (and possibly others like bookmarks, though I've not tested this particular case specifically).

Example: http://boffosocko.com/2017/07/11/the-facebook-algorithm-mom-problem/

**Comment by pfefferle** [comment]
I had a look at the code and you are right. For the moment you can disable the feature by setting the counter to `0` in the discussion options.

**Comment by pfefferle** [comment]
cc @snarfed

**Comment by pfefferle** [comment]
I would love to re-write it with unobtrusive jquery, so that the HTML do not really change.

Like: https://stackoverflow.com/questions/4054211/jquery-hide-show-list-items-after-nth-item

**Comment by snarfed** [comment]
sorry for the bug, and thanks for filing! fixed in #126.
