### ISSUE TITLE
Twitter mention with comment render as 'XXX mentioned this article', not the comment.

### ISSUE THREAD

**Issue by jackysee** [pfefferle/wordpress-semantic-linkbacks#128]
This [brid.gy post from twitter](https://brid-gy.appspot.com/post/twitter/jackysee/930972123161534464) is rendered as `XXX has mentioned this article...` in the [blog comment](https://jacky.seezone.net/2017/11/15/9015/#comment-203016). 

Meanwhile I have another similar [brid.gy post](https://brid-gy.appspot.com/post/twitter/jackysee/928446853611270146) rendered the comment text in the [blog comment](https://jacky.seezone.net/2017/11/08/8977/#comment-202972).

Both comments text do appear when I click edit comment in wordpress admin.

I checked that both semantic_linkbacks_type is `mention`, so wonder why the rendering is different?

**Comment by jackysee** [comment]
I found two things:
- the comment itself has unicode where `strlen` would count as about 288 characters, which is still within the 300 limit. (Actually it's 98 chinese character count)
- there are quotation mark in the comment get turned into html entities (i.e. `"` -> `&#8220;`) (by wordpress perhaps) Now we are at 302 characters.

**Comment by jackysee** [comment]
I think use `mb_strlen` and `html_entitiy_decode` would handle the case. 
Here is my test https://repl.it/repls/AdolescentEnergeticHarborporpoise 
But I wasn't sure if it's good to hard code the `UTF-8` encoding.

**Comment by pfefferle** [comment]
This is currently hardcoded (https://github.com/pfefferle/wordpress-semantic-linkbacks/blob/master/includes/class-linkbacks-handler.php#L4) and I think we should make it customizable.

**Comment by edent** [comment]
This is still an issue.  As a user, it isn't obvious why some of these are rendered as comments and others as mentions.

![Screenshot_2020-01-17 Comments (4) ‹ Terence Eden’s Blog — WordPress](https://user-images.githubusercontent.com/837136/72601624-aee7b400-390d-11ea-88e0-fc39a3c04a62.png)

This Webmention - https://brid-gy.appspot.com/post/twitter/edent/1218084305219571712 - is over 300 characters, for example.

Is there any reason to have a character limit?  Could the text be truncated after 300 characters?
