### ISSUE TITLE
Threaded comments

### ISSUE THREAD

**Issue by alohastone** [pfefferle/wordpress-semantic-linkbacks#130]
I was just wondering: does brid.gy store the information if a (facebook) comment is in reply to another (facebook) comment? And is there a way to display those comments as threaded comments in the wordpress comments section?

Since wordpress does have this functionality, I was wondering if it would be possible to use it to give more structure to discussions, and make them more readable.

Example: On facebook, it's quite clear which comments belong together:

![image](https://user-images.githubusercontent.com/3405023/33209592-d603a5a0-d116-11e7-90a4-a3c19460e218.png)

Link: https://www.facebook.com/alohaWEBLOG/posts/10155797692619890?comment_id=10155799756884890

On my wordpress site, the comments are sorted by time, descending:

http://www.alohastone.com/2017/11/15/sylabil-spill-zu-viel/

Which is fine if there's just a couple of comments that stand alone. But if you're replying to one or more specific comment(s), and there's severeal different discussions going on, sorting comments only by time might mess up the discussion.

I'm not a programmer, so I don't know if it's at all possible. But it might be a nice feature for future versions. What do you think?

**Comment by pfefferle** [comment]
I think this is a feature request for brid.gy @snarfed

**Comment by snarfed** [comment]
sure! i think bridgy actually supports this, and  think i've seen it work end to end into wordpress, but i don't have the post link handy.

this would just work by having `u-in-reply-to` point to the parent comment, as well as the post itself, right? (or arguably you could omit the post and use salmentions, but i haven't looked into that much myself.)

@pfefferle do the wordpress plugins detect `u-in-reply-to` links to sources to existing webmentions, and convert them to wordpress threaded comments?

**Comment by snarfed** [comment]
confirmed, bridgy currently supports this.

for example, here's the bridgy source page for the first child comment in @alohastone's screenshot, _ Kann ich leider nix mit anfangen. #imtoooldforthisshit_: https://brid-gy.appspot.com/comment/facebook/103109124889/10155797692619890/10155797692619890_10155799776699890

it has:
```html
  <a class="u-in-reply-to" href="https://www.facebook.com/103109124889/posts/10155797692619890"></a>
  <a class="u-in-reply-to" href="https://www.facebook.com/103109124889/posts/10155797692619890?comment_id=10155799756884890"></a>
  <a class="u-in-reply-to" href="http://www.alohastone.com/2017/11/15/sylabil-spill-zu-viel/"></a>
```

**Comment by dshanske** [comment]
This is worth testing.

**Comment by snarfed** [comment]
hey @alohastone, out of curiosity, in your wordpress's _Settings => Discussion_ page, is the threaded comments setting enabled? if not, try enabling it, then resend the webmentions in bridgy and see if they show up threaded then?

<img width="1211" alt="image" src="https://user-images.githubusercontent.com/778068/33281250-6e171ce8-d359-11e7-98a7-eba675b49193.png">

**Comment by alohastone** [comment]
Hey guys, hey @snarfed,

yes, I do have the threaded comments setting enabled 😊:

![threaded comments settings](https://user-images.githubusercontent.com/3405023/33291722-19c4f836-d3c7-11e7-93d4-375d5d60dd39.png)

I also did switch to SemPress theme real quick, just to rule out any theme issues. But even with SemPress, it doesn't show the FB comments as threaded comments. When using the reply-function in the wordpress comments section, it does work though. Even with my current theme.

![threaded comments wp](https://user-images.githubusercontent.com/3405023/33292014-0bed2872-d3c8-11e7-9096-305fe729401f.jpg)

**Comment by pfefferle** [comment]
@snarfed thanks for the info!

@alohastone sorry, but it SL does not support "u-in-reply-to" yet. There is a plugin for threaded comments, but this works a bit different: https://github.com/pfefferle/wordpress-webmention-for-comments

It sounds like a nice feature, so let's build it :)

**Comment by alohastone** [comment]
Oh yeah, I actually did have that other plugin of yours installed a while ago. But as SL was growing more and more, I was getting the impression that it's become obsolete. Would you recommend installing it again?

I'm still trying to get the hang of this webmention stuff. It's all very confusing at first, with all the different plugins and hard-to-find documentation..

Long story short: Thank you guys so much for your hard work. And thank you for being open to new ideas 😊 "pfefferle added the 'enhancement' label" 🎉 😁

**Comment by pfefferle** [comment]
@alohastone I would recommend using it... if I deprecate a plugin to merge it into the main, I mark it as `deprecated` like the webmention-form plugin: https://github.com/pfefferle/wordpress-webmention-form

I agree, that it is very confusing at the moment and I also agree, that the "feature plugin" stuff is also a bit awkward, but I work on them in my spare time, so most of the plugins, I experiment with, are highly unstable and I do not want to break the main one. Perhaps it is a good idea to document the different plugins a bit more in the Webmention `readme`.

BTW. @dshanske and @snarfed are working really hard to get all indieweb plugins more usable and to improve the UX, so I am convinced that this problem will also be fixed in the near future 😉 

You are welcome and thanks for your feedback 😁

**Comment by pfefferle** [comment]
We had a lot of discussions about that `tech problem` in the issue section of other plugins, if you are interested to join the discussion: https://github.com/indieweb/wordpress-uf2/issues/29#issuecomment-311496793

**Comment by dshanske** [comment]
@pfefferle With the comments merge into Webmention, do we want to revisit this?

**Comment by edent** [comment]
Just to add my support for this. And to add some examples.

* Paul replies to me - https://brid-gy.appspot.com/comment/twitter/edent/1211240890825682944/1211259320597405696
* Soph replies to Paul - https://brid-gy.appspot.com/comment/twitter/edent/1211240890825682944/1211259964301418496

Both come through correctly bridgy -> semantic-linkback -> WordPress comments.
But the "In reply to" isn't set for Soph's comment.
