### ISSUE TITLE
Language file update required?

### ISSUE THREAD

**Issue by alohastone** [pfefferle/wordpress-semantic-linkbacks#131]
Could it be possible that we do need an update for the language files?

When mouse-overing over the facepiles, I get some not-translated text

![translation mouse-over](https://user-images.githubusercontent.com/3405023/33210278-da824d9a-d119-11e7-9ecc-e09c9c4c405b.jpg)

In the wordpress dashboard comments section, the same issue is present:

![translation wordpress dashboard](https://user-images.githubusercontent.com/3405023/33210301-ea097252-d119-11e7-9d0b-c7cfb672147e.jpg)

**Comment by pfefferle** [comment]
Strange, it works perfect in my installation: https://notiz.blog/2017/10/04/readability/#comments
...and it is also translated: https://github.com/pfefferle/wordpress-semantic-linkbacks/blob/master/languages/semantic-linkbacks-de_DE.po#L101

The only change I can see is the lowercase "a" in your example... The translated version and the version in the code is with a capital "A": https://github.com/pfefferle/wordpress-semantic-linkbacks/blob/2133122b0f620124a3bc681e184bb1e96d6a92f5/includes/class-linkbacks-handler.php#L246

**Comment by alohastone** [comment]
Oh. Strange. I'll re-upload the language files then. Maybe I messed something up. Reporting back after the bath 🛀 😄

Thanks a lot! ❤️

**Comment by alohastone** [comment]
OK, got it. I disabled the [Post Kinds](https://de.wordpress.org/plugins/indieweb-post-kinds/) Plugin, and now everything works as expected.

As long as Post Kinds plugin is enabled, it seems to pull the information from there. If Post Kind is set to "article", it shows "hat this article auf facebook.com geliked". If no Post Kind is set, it shows "hat this  auf facebook.com geliked".

Soon as I disable the plugin, Semantic Linkbacks is using the Wordpress Post Format, and translating correctly.

**Comment by dshanske** [comment]
The solution is for someone to submit a translation for Post Kinds then.

**Comment by dshanske** [comment]
Any volunteers?

**Comment by alohastone** [comment]
I'll try to help – even though I'm not that familiar with plugin translations.

I opened the .pot file with POEdit, did some translations for testing purposes, and uploaded the .po and .mo files to the plugin directory. But the plugin doesn't seem to use the translations. What did I do wrong? Do I need to name them differently?

![untitled 2017-11-24 16-16-40](https://user-images.githubusercontent.com/3405023/33216147-ed418c84-d132-11e7-9fde-ea4da77bf49e.png)

**Comment by pfefferle** [comment]
This does not make any sense, except the post-kinds plugin is changing the text. @dshanske is that the case?

**Comment by pfefferle** [comment]
Ok, just found it... why do you overwrite the semantic linkbacks excerpt?

**Comment by dshanske** [comment]
I don't. I change it from post format to post kind.

**Comment by dshanske** [comment]
@alohastone Go to translate.wordpress.org, select the language and search for post kinds in plugin search. I use WordPress language packs.

**Comment by dshanske** [comment]
Or try this link.. https://translate.wordpress.org/projects/wp-plugins/indieweb-post-kinds

**Comment by pfefferle** [comment]
I will close this one, because it is not a SL problem, right?

**Comment by dshanske** [comment]
It isn't.
