### ISSUE TITLE
Plugin Hides "normal" comments

### ISSUE THREAD

**Issue by svnsbck** [pfefferle/wordpress-semantic-linkbacks#140]
I realized that the plugin seemingly hides "normal comments", i.e. those made on the site. Webmentions and likes work a charm. You can see this here:
https://svens.blog/2017/11/25/ia-writers-new-font/

Post shows the comment count, but the comments don't. With SL deactived they show up. Any ideas how I can quickly fix this?

All the best!

**Comment by pfefferle** [comment]
thanks for reporting! fixed in version 3.7.2.
