### ISSUE TITLE
Normal comments are not showing up anymore

### ISSUE THREAD

**Issue by remouk** [pfefferle/wordpress-semantic-linkbacks#141]
Hello,

If Semantic-Linkbacks is activated on WordPress, "normal" comments are not shown anymore below each article.

Sorry but this is a very annoying bug. I don't know when and what changed, but I hope you can fix it soon! :)

**Comment by pfefferle** [comment]
https://github.com/pfefferle/wordpress-semantic-linkbacks/issues/140

**Comment by pfefferle** [comment]
thanks for reporting! fixed in version 3.7.2.

**Comment by remouk** [comment]
Sorry didn't see #140 😅 Thanks for the fix, you ROCK!

**Comment by pfefferle** [comment]
No problem, I closed a way too early :)
