### ISSUE TITLE
Recommend removing h-as-* classes

### ISSUE THREAD

**Issue by gRegorLove** [pfefferle/wordpress-semantic-linkbacks#142]
Per https://indieweb.org/h-as

> h-as was an attempt to explicitly map ActivityStreams vocabulary 1:1 to microformats, and has been largely abandoned since it somewhat duplicates existing h-entry functionality, and also encourages explicit post typing which post creation UIs have largely abandoned in favor of more user-flexible optional properties, and post type discovery for any consuming code that claims to need explicit types.

**Comment by pfefferle** [comment]
Where have you seen `h-as-*` in the code?

**Comment by miklb** [comment]
I wonder if this was intended for post-kinds?

**Comment by dshanske** [comment]
https://github.com/pfefferle/wordpress-semantic-linkbacks/blob/master/includes/class-linkbacks-handler.php#L565

**Comment by dshanske** [comment]
Suggest closing this as committed in last PR

**Comment by gRegorLove** [comment]
#146 resolved this.
