### ISSUE TITLE
Reacji overlay emoji are broken

### ISSUE THREAD

**Issue by snarfed** [pfefferle/wordpress-semantic-linkbacks#154]
i tried updating recently, and noticed that the emoji overlays on the reaction faces are broken. :( not sure what caused it yet, but i was on bf0076f377aeb9b1981118b6dd1e23779bd54502 before (and i've reverted https://snarfed.org/ to that), and the relevant CSS hasn't changed since then, so i suspect markup changes are to blame. cc @dshanske.

i've tried firefox 57, chrome 63, and safari 11.0.2 on mac os x 10.13.2. all are similarly broken.

here's a screenshot in firefox, on my modified ryu theme. note the heart emoji is in the upper right corner.
<img width="1277" alt="image" src="https://user-images.githubusercontent.com/778068/34801648-a85605b2-f61e-11e7-8225-deffab70ceea.png">

and here's one in chrome, on twenty seventeen.
<img width="1156" alt="image" src="https://user-images.githubusercontent.com/778068/34801609-738a7bc4-f61e-11e7-8044-d44022a250be.png">

**Comment by snarfed** [comment]
here's the same page on my live site, still back on bf0076f377aeb9b1981118b6dd1e23779bd54502: https://snarfed.org/2017-10-31_25851

**Comment by dshanske** [comment]
I apologize. Not sure what I did to affect this. But will have a look.

**Comment by snarfed** [comment]
thank you @pfefferle! confirmed, this fixes it.

**Comment by pfefferle** [comment]
thanks for testing :)
