### ISSUE TITLE
RSVP invited

### ISSUE THREAD

**Issue by chrisaldrich** [pfefferle/wordpress-semantic-linkbacks#156]
When Brid.gy sends webmentions for people invited via a Facebook POSSE copy, the webmentions for these people don't show up properly in comments because `semantic_linkbacks_type` is set to "invite" instead of "rsvp:invited".

Manually effecting the change in the database provides the expected display. See: http://boffosocko.com/2018/02/14/homebrew-website-club-meetup-on-february-21-2018/#Invited

**Comment by dshanske** [comment]
Interestingly, I changed it based on an issue filed by @snarfed, #139
