### ISSUE TITLE
Implement schema.org microdata in comment walker?

### ISSUE THREAD

**Issue by asuh** [pfefferle/wordpress-semantic-linkbacks#157]
I found a nice example that includes schema.org attributes that would nicely complement what this comment walker is doing.
https://gist.github.com/georgiecel/9445357

Would they be of usable value to the comments?

**Comment by dshanske** [comment]
Does anyone consume them?

**Comment by asuh** [comment]
http://getschema.org/index.php/List_of_websites_using_Schema.org

**Comment by dshanske** [comment]
That's publishing.

**Comment by asuh** [comment]
Some are, yes. It seems more important than ever to include Schema microdata because Google, Microsoft, Yahoo and Yandex all consume it. There was a WordCamp LA SEO presentation advocating Schema markup in great detail

PDF presentation: https://2018.la.wordcamp.org/files/2018/08/SEO-101-WordCampLA-2018-compressed.pdf
