### ISSUE TITLE
GDPR complience

### ISSUE THREAD

**Issue by pfefferle** [pfefferle/wordpress-semantic-linkbacks#161]
- [ ] save only data that is really used and/or make it more transparent which data is stored: https://gdpr-info.eu/art-6-gdpr/

**Comment by dshanske** [comment]
We should definitely disclose what we are saving. I know Core WordPress is looking at GPDR tools for plugin developers to hook into. I would suggest a link in the settings to a privacy policy.

**Comment by dshanske** [comment]
https://indieweb.org/GDPR

**Comment by dshanske** [comment]
Personal sites are technically exempt though.

**Comment by dshanske** [comment]
In addition to a posted policy about what is collected, making it clear what it is used to do, we could make what is stored configurable.

**Comment by armingrewe** [comment]
Problem is that it's not entirely clear what constitutes a personal website, does it have to be exclusively for your relatives and friends or is it sufficient to have no advertising/otherwise commercial content? Try reading up on it online and from 5 websites you get 5 different views.

**Comment by dshanske** [comment]
How are we doing on this?
