### ISSUE TITLE
New MF2 has optional parsing dependency

### ISSUE THREAD

**Issue by dshanske** [pfefferle/wordpress-semantic-linkbacks#162]
The new version recommends an alternative parser that handles HTML5. Do we want to include it?

**Comment by dshanske** [comment]
Wondering if we should include the instructions as a note then

**Comment by pfefferle** [comment]
What is the benefit?

**Comment by dshanske** [comment]
"It is recommended to install the HTML5 parser for proper handling of HTML5 elements."

**Comment by pfefferle** [comment]
You can include the instructions, but this seems not very gen >= 3 friendly ;)

**Comment by dshanske** [comment]
Agreed, that is why it will be noted and linked, but not implemented.

**Comment by dshanske** [comment]
Closing this issue in favor of adding the instruction to webmention plugin in future.
