### ISSUE TITLE
Add blacklist and whitelist capabilities

### ISSUE THREAD

**Issue by dshanske** [pfefferle/wordpress-semantic-linkbacks#171]
We need some way to better moderate things. Some things to be auto approved, some blocked...as simple as possible.

**Comment by pfefferle** [comment]
Isn't this a Webmention Feature?

**Comment by dshanske** [comment]
We have more data here, so we can enhance it

**Comment by dshanske** [comment]
The idea is that the webmention blacklist would have a filter enhanced by this.

**Comment by dshanske** [comment]
Closed as this is implemented in Webmentions and we will be eventually merging.
