### ISSUE TITLE
Filepiles do not show  avatar, only author's name

### ISSUE THREAD

**Issue by jackysee** [pfefferle/wordpress-semantic-linkbacks#179]
It happens in recent upgrade.
The facepile in old/new comments only show author's name, not the avatar.
I've checked that the comment meta do have `semantic_linkbacks_avatar`.
My current theme would show the comment manually by using 

     <?php Linkbacks_Handler::show_mentions(); ?>

**Comment by armingrewe** [comment]
Seems to only happen with some themes, of my three blogs only one shows this problem (if memory serves me right it's the 2011 theme, in a rush just now, will check later)

**Comment by jackysee** [comment]
I debugged that `$allowed_comment_types`  in `pre_get_avatar_data()` do not have `webmention`.
The avatar shows after I tried to re-save webmention setting page.

While the case is solved, may consider why the setting is lost during upgrade.

**Comment by dshanske** [comment]
Webmention is set in the webmention plugin, because webmention has a setting for showing an avatar now. Will have to see about the default.
