### ISSUE TITLE
CSS+JS enqueued when chosing not to display facepile

### ISSUE THREAD

**Issue by sebastiangreger** [pfefferle/wordpress-semantic-linkbacks#181]
I am using only the "backend" features of the plugin, rolling my own custom frontend presentation. As it is currently set up, the plugin regardless adds semantic-linkbacks.css and semantic-linkbacks.js, along with jQuery (which my theme otherwise doesn't use), also if I disable all "facepile" types; the JS is only enqueued conditionally, if a "fold limit" has been set.

Probably not an issue when the plugin is used "as intended", nor do I have a specific suggestion to offer at this point (also not familiar enough with the entirety of the plugin), so just mentioning it as a special situation I observed.

As a workaround, to disable the embedding of unneeded CSS and JS, the following code can be used in the theme's _functions.php_ to override the plugin's script/style additions:

```
function my_deregister_scripts(){
  wp_dequeue_script( 'semantic-linkbacks' );
}
add_action( 'wp_print_scripts', 'my_deregister_scripts' );

function my_deregister_styles(){
  wp_dequeue_style( 'semantic-linkbacks-css' );
}
add_action( 'wp_print_styles', 'my_deregister_styles' );
```

**Comment by dshanske** [comment]
This is unnecessarily complicated...

`remove_action( 'wp_enqueue_scripts', array( 'Semantic_Linkbacks_Plugin', 'enqueue_scripts' ) );`

Removes them from being loaded in the first place.
