### ISSUE TITLE
Facepiles not displaying avatars

### ISSUE THREAD

**Issue by chrisaldrich** [pfefferle/wordpress-semantic-linkbacks#183]
Apparently the v3.7.7 update seems to break the display of avatar images in facepiles for likes, bookmarks, etc. Instead of showing the expected avatar image, it’s showing the author’s name wrapped with an href for the originating site.

It’s not just my site either as I notice that the facepiles at &lt;https://ramblinggit.com/2018/05/241/&gt; (using Sempress) are also displaying the same way.

I’d simultaneously updated the Webmention plugin and tried uninstalling and reinstalling both plugins as well as checking a variety of settings (including the discussion setting for showing Avatars) and uninstalling a variety of potential conflicting plugins, but to no avail.

I know there were recent changes for privacy related pieces, perhaps this is the cause?

(Originally published at: https://boffosocko.com/2018/05/31/facepiles-not-displaying-avatars/)

**Comment by dshanske** [comment]
The only way it would show that is if the avatar settings in the webmention plugin weren't set

**Comment by troutcolor** [comment]
@chrisaldrich 
I had the same problem. After reading this I turned ' Show avatars on webmentions if available' off saved and turned on again. This fixed it.

**Comment by armingrewe** [comment]
@troutcolor thanks for that hint, that fixed it for me as well. Strangely enough I only had that problem on one of my three blogs (all using different themes though).

**Comment by dshanske** [comment]
That may be why I had issues reproducing it

**Comment by dshanske** [comment]
This is a webmention plugin issue now though
