### ISSUE TITLE
Change default avatar

### ISSUE THREAD

**Issue by pfefferle** [pfefferle/wordpress-semantic-linkbacks#184]
I received some mails from users, that thinks the "spy" default avatar, looks too much like spam or phishing... We should think about a more neutral avatar...

Perhaps: https://commons.wikimedia.org/wiki/File:Faenza-avatar-default-symbolic.svg

**Comment by pfefferle** [comment]
cc @dshanske

**Comment by dshanske** [comment]
It's a spy? Oh well. I wanted something neutral

**Comment by dshanske** [comment]
I don't want to get into the avatar area as I think it is out of scope. I just want to ensure that there is a way to give mentions a generic icon that doesn't need gravatar as we know that more often than not there is no email to try.

**Comment by dshanske** [comment]
Change reverted in last commit

**Comment by dshanske** [comment]
@pfefferle Can we close this?
