### ISSUE TITLE
Fatal error submitting comment

### ISSUE THREAD

**Issue by colin-walker** [pfefferle/wordpress-semantic-linkbacks#197]
When submitting a comment with WordPress email notifications enabled get the following:

```Fatal error: Uncaught Error: Call to undefined function Linkbacks_Handlerget_type() in /home/colinwalker/public_html/wp-content/plugins/semantic-linkbacks/includes/class-linkbacks-notifications.php:80 Stack trace: #0 /home/colinwalker/public_html/wp-includes/class-wp-hook.php(286): Linkbacks_Notifications::comment_notification_text('New comment on ...', '54977') #1 /home/colinwalker/public_html/wp-includes/plugin.php(203): WP_Hook->apply_filters('New comment on ...', Array) #2 /home/colinwalker/public_html/wp-includes/pluggable.php(1544): apply_filters('comment_notific...', 'New comment on ...', '54977') #3 /home/colinwalker/public_html/wp-includes/comment.php(2098): wp_notify_postauthor(54977) #4 /home/colinwalker/public_html/wp-includes/class-wp-hook.php(288): wp_new_comment_notify_postauthor(54977) #5 /home/colinwalker/public_html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(false, Array) #6 /home/colinwalker/public_html/wp-includes/plugin.php(453): WP_Hook->do_action(Array) #7 /home/colinwalker/public_ht in /home/colinwalker/public_html/wp-content/plugins/semantic-linkbacks/includes/class-linkbacks-notifications.php on line 80```

This causes a 405 error on wp-comments-post.php

**Comment by colin-walker** [comment]
Line 80 should be:

```if( ! Linkbacks_Handler::get_type)( $comment ) ) {```

The ```::``` is missing.

**Comment by pfefferle** [comment]
closed with your merge request! thanks again :)
