### ISSUE TITLE
Facepile not showing when comments are disabled

### ISSUE THREAD

**Issue by iamwebrocker** [pfefferle/wordpress-semantic-linkbacks#207]
This is only an issue when disabling comments after some comments or reactions already happened. In my blog comments are disabled automatically after 4 weeks.

With the regular comments, if comments are disabled, only the comment-form will be disabled. The list of comments will still be visible.
With the facepile(s) however, if comments are disabled, both the comment-form and the facepile(s) disappear. Regular comments are still visible.
I expected both comments and reactions/facepile to be visible.

It seems that the display of the facepile is somehow tied to the `comment_form()` wp function, or that the display is dependent on a filter that is used in this context…? (At least the facepile markup appears inside my theme in the wrapper-div that is only used for the `comment_form()` output.)

```
function comment_form( $args = array(), $post_id = null ) {
    if ( null === $post_id )
        $post_id = get_the_ID();
 
    // Exit the function when comments for the post are closed.
    if ( ! comments_open( $post_id ) ) {
        /**
         * Fires after the comment form if comments are closed.
         *
         * @since 3.0.0
         */
        do_action( 'comment_form_comments_closed' );
 
        return;
    }
(...)
```

Since `comment_form()` returns early when comments are disabled, probably the hooked action (?) to display the facepiles is never reached.

Possibly related: https://github.com/pfefferle/wordpress-webmention/issues/190

**Comment by dshanske** [comment]
Automatically disable facepiles if comments are disabled is a possibility

**Comment by iamwebrocker** [comment]
Hm, if this is the desired behavior I think an option for this in the settings page would be great to have the facepile showing when comments are disabled.
Currently the behavior is inconsistent with the display of the "normal" comments (which are shown) -- so I'd expected the facepile to behave the same.

**Comment by iamwebrocker** [comment]
I thought some more about this and maybe this is more complex than I originally assumed.

The original, WordPress comments, way is this: If comments are disabled, essentially _commenting_ is disabled. The comment form is not shown, so from this moment on no new comments are possible.
Older comments however are displayed.

Translating this to the indieweb 'reactions' would mean that the possibility to receive reactions for the post has to be connected to the 'enable/disable' comments. Or even better, a separate settings to enable/disable webmentions for a specific post?

currently only the _display_ of the webmentions/facepile is tied to the 'comments enable/disable' setting, no comments, no facepile, which I think makes sense for posts that have the comments disabled from the beginning -- asuming the author doesn't want to have comments or reactions showing. But since the post is receiving webmentions no matter what the setting for the comments is, it can only be controlled on the display side -- and this is then a problem for posts that had comments enabled and already had comments and webmentions coming in, which is the case I described above.

Trying to break this down:

Are webmentions the same breed as comments?

Is it wise to tie them to the state of comments (enable/disable)?

If so, what would be the equivalent of disabling the comment form for webmentions?

The display of webmentions/facepile should be independent from the state of comments, already received webmention should not be hidden when a posts comments status is set to disabled, or should also be a setting in the admin.

Not showing the facepile, treating it the same way as the comment form feels wrong to me. The comment form is the source of comments for the post, if comments are dsiabled, the source is made unavailable, not the display of comments. The same logic should apply for the webmentions.

**Comment by pfefferle** [comment]
why not also use the `comment_form_comments_closed` hook? should be that simple?!?

**Comment by iamwebrocker** [comment]
Thanks @pfefferle <345! 
/worksforme

**Comment by pfefferle** [comment]
I thank you for the tip with the disabled hook 😉

**Comment by iamwebrocker** [comment]
:-) I still wonder if tying this to the comment form display is the right approach, esp since it is more like the ping status. But I see why having a dedicated template function like "webmention_facepile()" would cause trouble for non-savvy users/admins with or with standard templates, so I'm happy with /worksforme ;-)
