### ISSUE TITLE
when source contains both semantic link and mention, prioritize semantic link

### ISSUE THREAD

**Issue by snarfed** [pfefferle/wordpress-semantic-linkbacks#21]
i recently ran into this when all of the bridgy webmentions on a post of mine showed up as plain mentions instead of favorites, retweets, etc: https://snarfed.org/2015-03-07_huffduff-video

in this specific case, the bridgy source mf2 for each response has both a mention link and a like/repost/etc link, e.g. https://brid-gy.appspot.com/repost/twitter/schnarfed/574460993398427649/574962900458205184 :

```html
<div class="e-content">
RT <a href="https://twitter.com/schnarfed">@schnarfed</a>: huffduff-video lets you send @Huffduffer the audio from videos on YouTube, Vimeo, and more! snarfed.org/2015-03-07_huf… huffduff-video.snarfed.org
<a class="u-mention" href="https://snarfed.org/2015-03-07_huffduff-video"></a>
</div>
<a class="u-repost u-repost-of" href="https://twitter.com/schnarfed/status/574460993398427649"></a>
```

when the plugin handles this mf2, it sees the `u-mention` link first, so it stores `semantic_linkbacks_type = mention` in `wp_commentmeta` and the wordpress comment gets rendered as a mention. if i remove the mention link and resend the webmention, it sees the `u-repost-of` link and correctly stores `semantic_linkbacks_type = repost`.

it should probably instead look at all of the links to target in the mf2, and if any of them are semantic, those should be prioritized over mention, right?

thanks in advance! cc @dshanske

**Comment by pfefferle** [comment]
This is no combination of two different semantics... Your code says that the snarfed link was "mentioned" and that the twitter link is "reposted". The plugin checks the semantic of the link that was pinged and should ignore all other links (because they might be in another context). So it seems no bug that it uses the "mention" but it seems to be a bug that it uses the "repost" if you remove the first link.

**Comment by snarfed** [comment]
oops, sorry, i made a mistake trimming that example source mf2. it actually had both the snarfed.org and twitter.com links as both mentions and reposts, but i think i reproduced this behavior with just:

```html
<div class="e-content">
RT <a href="https://twitter.com/schnarfed">@schnarfed</a>: huffduff-video lets you send @Huffduffer the audio from videos on YouTube, Vimeo, and more! snarfed.org/2015-03-07_huf… huffduff-video.snarfed.org
<a class="u-mention" href="https://snarfed.org/2015-03-07_huffduff-video"></a>
</div>
<a class="u-repost u-repost-of" href="https://snarfed.org/2015-03-07_huffduff-video"></a>
```

**Comment by pfefferle** [comment]
OK, then it surely should use "repost" instead of "mention".

**Comment by pfefferle** [comment]
the version 3.1.0 should work better, but I think I have to implement a prio list if I find the time...
