### ISSUE TITLE
Possibility to define the output via theme

### ISSUE THREAD

**Issue by chrisbergr** [pfefferle/wordpress-semantic-linkbacks#210]
Hi Matthias,

as always, it would be great **to have a setting to deactivate the plugin's css file**.
Maybe the siteowner or theme developer would like to have other styles or merged the styles into one file due to performance reasons.

The other and more complex enhancement is the use of either template files or action hooks in the comments walker to give the theme the possibility to overwrite the html output. The `post-kinds` plugin is a good example how to do so.

**For example**: I love the functionalities of the plugin which saves rich data of the received mentions, the function to get the counts of every specific type and so on. But I'd like to let the normal comments and replies look like how I defined the comments in my theme and display the facepiles on another location.

I hope I described my request understandable and I hope you also see this as a great improvement of this plugin.

**Comment by pfefferle** [comment]
Have you tried https://codex.wordpress.org/Function_Reference/wp_dequeue_style ??? Is this working for you or do you prefer a CONST or a filter or something similar?

**Comment by chrisbergr** [comment]
Of course I get the desired result with the function 'wp_dequeue_style'. But it would be more elegant with a checkbox on a settings page in the admin interface, in order not to register the style sheet at all.

But that's just the side request.

Actually, the templates are much more important to me.

**Comment by chrisbergr** [comment]
I have a proposal for you. See [my fork](https://github.com/chrisbergr/wordpress-semantic-linkbacks/tree/templates-for-mentions). Maybe you'd be able to test this on your test environment? It worked great in my local env with all my tests.

**Comment by dshanske** [comment]
I like the idea, but have a slightly different idea on implementation.

**Comment by chrisbergr** [comment]
I'm looking forward to see how you would implement this.

**Comment by chrisbergr** [comment]
In case anyone wants to see something, here is a demo implementation: https://ambersaunders.de/uncategorized/hello-world/

Theme: https://github.com/chrisbergr/Themeberger-Test
