### ISSUE TITLE
do not add mf2 to default comment author avatar

### ISSUE THREAD

**Issue by sknebel** [pfefferle/wordpress-semantic-linkbacks#215]
Right now it seems that if a comment author has no avatar, the displayed default image is still marked up as `u-photo`. This shouldn't happen. (Observed this on jgmac1106's site, which is running the indieweb-2016 theme, in case the theme is relevant for this)

**Comment by dshanske** [comment]
This should now be doable now that we are hosting the default locally instead of WordPress serving even the anonymous avatars through Gravatar
