### ISSUE TITLE
Add filter on hostname in Comment Walker

### ISSUE THREAD

**Issue by dshanske** [pfefferle/wordpress-semantic-linkbacks#218]
If a comment is a webmention, it adds @example.com to the display.

Want to make this filterable so it could be replaced with an icon.

**Comment by dshanske** [comment]
Maybe look at some additional placements for themes to customize

**Comment by snarfed** [comment]
yes! i'd vote for an option to add icons themselves. i know this plugin doesn't currently bundle them, but i think it'd be fine to add them. (and worst case, if users who also have synd links get the bundle twice, that's not really so bad.)

**Comment by dshanske** [comment]
Syndication Links uses an svg sprite. Per request about the growing size of the sprite, I was going to look at inline svg instead. My plan was, as part of that. to see about a smaller subset of icons built in of current and past Bridgy backfeed services and allow for more optionally
