### ISSUE TITLE
Comment database entry is empty

### ISSUE THREAD

**Issue by sebastiangreger** [pfefferle/wordpress-semantic-linkbacks#219]
Sorry for this being a rather unspecific issue report. I spent over an hour tracing the problem, but do not seem to find the key to solving it.

I am using wordpress-webmention and wordpress-semantic-linkback, and webmentions in general work fine. However, today I received a webmention from this [source](https://marcthiele.com/notes/thanks-for-the-mention-sebastian) to this [target](https://sebastiangreger.net/2019/02/events-germany-summer-2019/), which created a comment in the database, but all fields are empty.

Debugging, I was able to trace the issue to https://github.com/pfefferle/wordpress-semantic-linkbacks/blob/29dcda5973f356cd3f4c7d024128e74f371c71df/includes/class-linkbacks-mf2-handler.php#L159 - the function returns an empty array, which means that $commentdata, which still contained all the webmention's data before it was called is then empty.

The function gets called by filter _semantic_linkbacks_commentdata_ - before the line https://github.com/pfefferle/wordpress-semantic-linkbacks/blob/29dcda5973f356cd3f4c7d024128e74f371c71df/includes/class-linkbacks-handler.php#L202 $commentdata is fine, after the call it is empty.

Erasing the entire comment data and creating an empty comment (maybe due to a malformed markup? ...I lack the background to dig deeper) is probably not desired behaviour?

**Comment by pfefferle** [comment]
It is indeed a problem of the markup, because Marc does not use `h-entry` on his website, but you are right, it should not save empty fields in this case. Thanks for reporting.

**Comment by pfefferle** [comment]
Hmm... but it seems that Marc does not use any possible fallback (OpenGraph, meta-description) so there is no way to get any data. But the plugin should show a message like "... mentioned this ... on ..." or show a facepile?!?

**Comment by edent** [comment]
This is what's causing the issues in https://github.com/pfefferle/wordpress-webmention/issues/289

**Comment by edent** [comment]
Replacing `return array();` with `return $commentdata;` seems to fix it. That allows it to be an "unenhanced" Webmention.

**Comment by pfefferle** [comment]
Good point... If there are no MF(2)s in the site it would be blank otherwise!
