### ISSUE TITLE
Parsing in-reply-to as a compound object

### ISSUE THREAD

**Issue by gRegorLove** [pfefferle/wordpress-semantic-linkbacks#22]
My [reply](http://gregorlove.com/notes/2015/03/22/1/) to @snarfed's [post](https://snarfed.org/easy-indieweb-interactions-on-android) is not showing the contents of my reply on his site, only that I "replied on gregorlove.com." We think this might be because my `in-reply-to` has a nested `h-cite` instead of a simple text string (or array of strings).

Reference: http://indiewebcamp.com/irc/2015-03-22#t1427041811926

**Comment by snarfed** [comment]
+1. thanks for filing @gRegorLove!

**Comment by dshanske** [comment]
It isn't that. It is a bug of sorts.

https://github.com/pfefferle/wordpress-semantic-linkbacks/commit/c363691d22abad0367b9f28dbc9b395ffd8b3f7d#diff-046d4632e7cce0b44f8c9a9a94458de6L127

Rollback this change.

**Comment by pfefferle** [comment]
should be fixed now
