### ISSUE TITLE
Some approved comments become invisible when this plugin is activated.

### ISSUE THREAD

**Issue by jasonshew** [pfefferle/wordpress-semantic-linkbacks#223]
**When this plugin is activated, only 4 out of 5 comments are visible:**

> ![img](https://raw.githubusercontent.com/jasonshew/jasonshew.github.io/master/Screen%20Shot%202019-04-28%20at%2023.55.05.png)

**When this plugin is deactivated, all of the 5 comments are visible:**

> ![img](https://raw.githubusercontent.com/jasonshew/jasonshew.github.io/master/Screen%20Shot%202019-04-28%20at%2023.59.47.png)

The 5 comments are always approved and thus visible from the backend dashboard and the comment feed.

Please fix it. Thanks!

**Comment by khurtwilliams** [comment]
Might this be similar to this one: https://github.com/pfefferle/wordpress-semantic-linkbacks/issues/222
