### ISSUE TITLE
HTML5 comments seems to overwrite facepiles

### ISSUE THREAD

**Issue by pfefferle** [pfefferle/wordpress-semantic-linkbacks#227]
@dshanske it seems that the html5 implementation (https://github.com/pfefferle/wordpress-semantic-linkbacks/blob/master/includes/class-linkbacks-walker-comment.php#L77) in the comment walker is disabling the facepile feature in some way.

Conversation: https://wordpress.org/support/topic/unable-to-show-facepile/

**Comment by prtksxna** [comment]
So I installed https://github.com/pfefferle/Autonomie on my site and tested it, and I still don’t get a facepile: https://imgur.com/a/n3F7aJV (my [theme](https://github.com/prtksxna/zuari) on this [page](https://prtksxna.com/2019/07/25/goa-homebrew-website-club-1/) )

Also, I double-checked, I am on version `3.9.3` of this plugin.

**Comment by pfefferle** [comment]
@prtksxna if you checked other themes, it seems not what I thought.

**Comment by pfefferle** [comment]
@prtksxna can you please send me a picture of your settings?

**Comment by dshanske** [comment]
I will have a look at this when I can to see if I see something. I haven't been in this code in ages.

**Comment by prtksxna** [comment]
@pfefferle Here you go:

![wpsettings](https://user-images.githubusercontent.com/9491/62381302-d073ff80-b568-11e9-9b6e-0fb6268d3ea2.png)

Let me know if you'd like to see any other setting/page too.

**Comment by prtksxna** [comment]
Hey o/ Any updates on this? I recently updated the plugin but still get the same issue.

**Comment by prtksxna** [comment]
This can be closed now that #240 is fixed.
