### ISSUE TITLE
Accessibility - can't click on Facepile labels

### ISSUE THREAD

**Issue by edent** [pfefferle/wordpress-semantic-linkbacks#232]
I can't click on the text labels next to the Facepile checkboxes:
![List of checkboxes](https://user-images.githubusercontent.com/837136/71369252-10806100-25a2-11ea-9123-07b05ac92221.png)

The cause is:
https://github.com/pfefferle/wordpress-semantic-linkbacks/blob/master/semantic-linkbacks.php#L96

```
printf( '<input name="semantic_linkbacks_facepiles[]" type="checkbox" value="%1$s" %2$s />%3$s<br />', $key, checked( in_array( $key, $facepile, true ), true, false ), $value );
```

The correct output should be something like:

```
<input name="semantic_linkbacks_facepiles[]" type="checkbox" value="mention" checked="checked" id="mention">
<label for="mention">Mention</label><br>;
```

This will require adding an `id` to each `input`. Would you like me to create a PR for this?

**Comment by dshanske** [comment]
There are plans to rewrite this functionality as part of merging this plug-in into webmentions...but in the interim, please do submit the pr and we'll merge it as there is no definite timetable for the bigger project

**Comment by edent** [comment]
Done.
