### ISSUE TITLE
Images in Tweets from Bridgy not being included

### ISSUE THREAD

**Issue by edent** [pfefferle/wordpress-semantic-linkbacks#235]
(Not sure if this is a problem with the plugin, or Bridgy - feel free to correct me)

Images from Tweet replies aren't included in comments.

This tweet - https://twitter.com/Gadgetoid/status/1209423035398311937 - has an image.

It gets rendered as this HTML from Bridgy - https://brid-gy.appspot.com/comment/twitter/edent/1209420474964496385/1209423035398311937

I *think* the issue is that the `<img>` is outside of the `<div>`

```
<div class="e-content p-name">
  I went on a Wednesday 😂
  <a class="u-mention" href="http://edent.tel/"></a>
  <a class="u-mention" href="https://shkspr.mobi/blog/"></a>
  <a class="u-mention" href="https://twitter.com/edent"></a>
</div>
<img class="u-photo" src="https://pbs.twimg.com/media/EMi71kMWsAIUuxu.jpg" alt="" />
```

So the comment looks like this, with no image:
![Screenshot_2019-12-25 Comments (1) ‹ Terence Eden’s Blog — WordPress](https://user-images.githubusercontent.com/837136/71438830-1d5e9b00-26ef-11ea-9b07-27aec0657a31.png)

**Comment by dshanske** [comment]
This is the plugin.
