### ISSUE TITLE
Appropriate settings location detection broken.

### ISSUE THREAD

**Issue by tw2113** [pfefferle/wordpress-semantic-linkbacks#236]
In WordPress Webmention plugin, and https://github.com/pfefferle/wordpress-webmention/commit/53dd363fb659c91ce6c57412b33244185892eab3 the "Webmention_Plugin" class was removed from the loader file and not replaced.

This removal is causing the settings for Semantic Linkbacks to always fall to the WordPress core "Discussion" settings page, regardless of Webmention plugin usage.

Unsure if we want to rely on a different class or procedural function being defined, or if we want to perhaps make use of a defined constant that's used in Webmention.

**Comment by bekopharm** [comment]
I can not find the settings anywhere. No menu item, no `settings` on Plugin Listing, nothing in General or Discussion. It is activated. That's all I see.

Semantic-Linkbacks version 3.10.1

**Comment by dshanske** [comment]
Did you check under webmentions?

**Comment by bekopharm** [comment]
Ah, there it is. Hiding in plain sight. Thank you @dshanske :D
