### ISSUE TITLE
Facepile and headings not showing in version 3.10

### ISSUE THREAD

**Issue by frankmeeuwsen** [pfefferle/wordpress-semantic-linkbacks#237]
Here's my situation: I use the Indieweb Publisher theme from @dshanske with some small tweaks in the design in a child theme. I have various Indieweb plugins enabled. 
When I updated the Linkbacks plugin from 3.9.2 to 3.10, all of a sudden all my facepiles and headings for Likes, reposts and mentions disappeared. Right now all comments are shown as a list. You can see an example on [this older blogpost](https://diggingthedigital.com/indiewebcamp-utrecht-aanmeldingen-zijn-open/) with various linkbacks from Twitter and reposts. 

In my local development environment I still had 3.9.2 enabled and it still showed the proper format of headings and facepiles. The moment I updated to 3.10 it was gone. 

Here's what I did on my local development environment to narrow down on the possible problem

- I disabled all other plugins (including Jetpack) with version 3.10 still enabled. The problem persists
- I rolled back to 3.9.2 with a download from the repo. I get the headings back but somehow it doesn't show the avatars ([screenshot](https://dsc.cloud/triggi/theoreticalism-playingly-stravaig-uskara.png))
- I removed the plugin. Re-installed the version 3.9.2. The headings are still there, but still no Twitter avatars.
- Activated the Indieweb Publisher theme instead of the child theme, no change.
- Activated the default Twenty Twenty theme. Headings are still there but still no avatars.
- Loaded the page in a private browserwindow, without adblockers, trackers and other extensions that might block Twitter avatars. Still nothing to see.

The moment I update to 3.9.3 or 3.10 on my local machine, I see the same lay-out as the live version linked above.

So... I actually have no idea how to move on now. I want to roll back to 3.9.2 for the time being but I would like to see the avatars of the commenters. But maybe is there something else to try? 

What can I do?

**Comment by frankmeeuwsen** [comment]
To add to (my) confusion, I also have a testsite on https://frankmeeuwsen.xyz/ This also has the Indieweb Publisher theme with my own childtheme. I also have version 3.10 of the plugin. But on this testsite, the lay-out is even more different. You can see on [this blogpost](https://frankmeeuwsen.xyz/2019/11/03/webmention-op-domein/#webmentions) how it shows. 

- Likes are shown between the commentform and webmention form
- Below the comments there's another list of the webmentions. 

I am not sure how this is done and how it relates to the problem above but I thought I'd mention this as well.

**Comment by dshanske** [comment]
It shouldn't have done anything...it didn't touch the facepile code...odd

**Comment by dshanske** [comment]
Is there anything in the error log because I have several in mine.

**Comment by frankmeeuwsen** [comment]
Where and how can I find an error log?

**Comment by frankmeeuwsen** [comment]
After some digging through the code and just trying different outputs I was about to give up. I decided to do one more thing on my local development environment. In the Indieweb > Webmention settings I unchecked one option for the facepiles, saved it, checked it again and saved. That's all I did. When I reloaded the page, all of a sudden the headings and facepiles are back. 

I tried the same on my live website. Oddly, I have the same version of the plugin (3.10) but the options are not under the Webmention settings yet but still under Settings > Discussion. Even though, I did the same thing. Uncheck an option for the automatic embed facepiles, saved it. Checked it and saved. Reload the page and bam, facepiles and headings are back.

What I take from this as a non-developer, when I update the plugin, I need to sort of reset the settings by saving them again with some different settings. That should not be necessary right?

I will also deactivate, remove, download and activate the plugin on my live server to see if the settings appear at the Webmention settings again.

**Comment by armingrewe** [comment]
Sorry, only see this now. This is pretty much what I would have recommended to try. I can't remember the details, but I remember we had a similar problem before and this was exactly the solution to fix it.

I don't think this is regular occurrence, I've upgraded to 3.10 without any issues, but vaguely remember having a similar problem at one upgrade in the past.

**Comment by pfefferle** [comment]
Can you re-test it with the latest version?

**Comment by frankmeeuwsen** [comment]
@pfefferle Everything works as it should now!
