### ISSUE TITLE
Checked facepile settings aren't actually active

### ISSUE THREAD

**Issue by prtksxna** [pfefferle/wordpress-semantic-linkbacks#240]
On a fresh WordPress install when you install only this plugin (no WebMention or any other plugin) and go to the Discussions settings, under _Automatically embed facepiles_, you see this:

<img width="371" alt="Screenshot 2020-04-07 at 4 38 14 PM" src="https://user-images.githubusercontent.com/9491/78662538-34b44380-78ee-11ea-98ce-ff3d6d981bd5.png">

But if you do a `var_dump` of `get_option( 'semantic_linkbacks_facepiles', array() );` you get an empty array and so no facepiles are shown. 

**As a user I fixed this** by unchecking _Reacji_ and saving the settings. This made facepiles show up. I then checked _Reacji_ again and saved, and the facepiles are still showing since the settings aren't empty any more.

This might be related to #237 and #227

**Comment by pfefferle** [comment]
OK, then it is a problem with default settings

**Comment by pfefferle** [comment]
@prtksxna thanks for debugging! can you verify my change?

**Comment by prtksxna** [comment]
Thank you for such a quick fix 🔥
Sure, I'll spin up a new instance tomorrow and let you know 😊

**Comment by pfefferle** [comment]
cool, thanks!

**Comment by prtksxna** [comment]
Works! Thank you again @pfefferle.

**Comment by pfefferle** [comment]
Thanks for testing! I released the new version with that fix: https://github.com/pfefferle/wordpress-semantic-linkbacks/releases/tag/3.10.2
