### ISSUE TITLE
facepiles obscure what used to be pingbacks

### ISSUE THREAD

**Issue by jgoerzen** [pfefferle/wordpress-semantic-linkbacks#249]
Frequently I will mention an article on my site in a later article.  For instance, https://changelog.complete.org/archives/10053-the-incredible-disaster-of-python-3 is mentioned in https://changelog.complete.org/archives/10063-the-fundamental-problem-in-python-3.  In the latter, I used to see a nice thing in the comments section saying that my newer article had mentioned the older one.

Now there is just a thing in "mentions", and that doesn't go to the new article at all, but rather just to my author page.  It is pretty much hidden.  And I can't find a way to turn this off; the option to remove facepiles is now gone.  The mentions also used to form a nice way to see what people were waying about the post; now not only is that information not presented, but it doesn't present a link to the mention itself, either.

However, disabling Semantic Linkbacks itself leads to all manner of bad results, a bunch of comments saying "This Article was mentioned on brid-gy.appspot.com" and other articles on my website that mention it are now included IN FULL in the comment, rather than just by subject.

Look at https://web.archive.org/web/20191219052255/https://changelog.complete.org/archives/10053-the-incredible-disaster-of-python-3 for instance, and see how the twitter mentions actually contribute to the conversation.

I don't know exactly what changed, though recently the bridgy plugin I used to have got deprecated and removed, and I added ActivityPub, though I don't think either of them should have made this difference.

**Comment by dshanske** [comment]
The Bridgy plugin was subsumed into the Syndication Links plugin. Nothing has changed with Semantic Linkbacks in ages, to be honest. We have been working on merging it into the webmentions plugin, so only maintenance releases have occurred, and the merge is a big rewrite of code, so...it is slow coming. We can look at some fixes to adjust this for self-mentions.

Keep Semantic Linkbacks enabled, but in the webmentions settings, try unclicking that mentions should be facepiled and they should return to being displayed elsewhere and they should get the data enhancements that wouldn't show brid.gy.

**Comment by jgoerzen** [comment]
Hi!  I have no option in webmention to disable facepiles, unfortunately - I did look!  Here's the only relevant settings I can see in Webmention:

![webmention](https://user-images.githubusercontent.com/112925/102438920-d8f49b00-3fe2-11eb-8aed-d2b6d4a136eb.png)

Thanks!

**Comment by dshanske** [comment]
Disable it for all of the types there.

**Comment by jgoerzen** [comment]
Ahh, perfect!  I misunderstood what that meant (I thought it had to do with picking avatars, rather than generating the facepiles to begin with.)  Thank you!
