### ISSUE TITLE
Comment Notification Presentation

### ISSUE THREAD

**Issue by dshanske** [pfefferle/wordpress-semantic-linkbacks#25]
WordPress has a series of filters off its wp_notify_postauthor function to customize that presentation.

https://developer.wordpress.org/reference/functions/wp_notify_postauthor/#source-code

When I receive a notification of a comment generated through a combination of Bridgy and Semantic Linkbacks, it looks something like this...

Author: Bridgy Response (IP: 107.178.195.220, 220.195.178.107.gae.googleusercontent.com)
E-mail:
URL: https://brid-gy.appspot.com/like/facebook/100002356503167/858841630871046/10154036849115445
Whois: http://whois.arin.net/rest/ip/107.178.195.220
Comment:
This Article was mentioned on <a href="https://brid-gy.appspot.com/like/facebook/100002356503167/858841630871046/10154036849115445" rel="nofollow">brid-gy.appspot.com</a>

It should be trivial to use the same presentation logic to make the notification readable.

**Comment by pfefferle** [comment]
Sadly there seems to be no `filter` to change the author of a comment.

**Comment by dshanske** [comment]
But the body can be changed.

**Comment by dshanske** [comment]
I think I can improve the presentation on this. I'll be sending a PR when I get to writing one.
