### ISSUE TITLE
Fatal error: must be of type Countable

### ISSUE THREAD

**Issue by bekopharm** [pfefferle/wordpress-semantic-linkbacks#258]
Semantic-Linkbacks 3.11.0 
Wordpress  5.8.3
PHP 8.0

A Webmention didn't make it due to an Fatal Error at this line: https://github.com/pfefferle/wordpress-semantic-linkbacks/blob/3e70f3c1b137eba9a246167ff3d2ee14541eeb51/includes/class-linkbacks-mf2-handler.php#L399 

> PHP Fatal error:  Uncaught TypeError: count(): Argument #1 ($item) must be of type Countable|array

For unknown reasons `$item` was `undefined`.

The Webmention in question was `https://php.microformats.io/?url=https%3A%2F%2Finhji.de%2Fnotes%2F1644845272`

I added this little hack to `wp-content/plugins/semantic-linkbacks/includes/class-linkbacks-mf2-handler.php`:

```php
        public static function flatten_microformats( $item ) {
                $flat = array();
                if(!$item) {
                        return $flat;
                }
                if ( 1 === count( $item ) ) {
```

And pulled it in manually via `wp-json/webmention/1.0/endpoint`. The Webmention is now live.

**Comment by pfefferle** [comment]
Would you like to make a PR for the change?

**Comment by lordmatt** [comment]
Can confirm. Some static functions return null when they give up but nulls are not checked for. I used a similar hack.

**Comment by bekopharm** [comment]
Don't have a dev system set up and I'm unaware of side effects so I don't feel comfortable with a PR at this point.

**Comment by pfefferle** [comment]
No problem!

**Comment by bekopharm** [comment]
Good thing I noted this down. Some update removed my hack again and it started failing again.
