### ISSUE TITLE
Change Comment Classes

### ISSUE THREAD

**Issue by dshanske** [pfefferle/wordpress-semantic-linkbacks#26]
Change h-as-* to u-*...

Example: h-as-reply would turn to u-reply. 

http://indiewebcamp.com/irc/2015-06-09/line/1433880387532

**Comment by pfefferle** [comment]
I don't think `u-` is the correct prefix, because a comment is not a link, but we can use `p-reply` instead.

**Comment by dshanske** [comment]
Yes, but a webmention is.

**Comment by pfefferle** [comment]
But not technically... It is a div or an article... and `u-` is per definition only for link elements http://microformats.org/wiki/microformats-2-prefixes
