### ISSUE TITLE
Parse Elements of Source URL and save as Comment Meta

### ISSUE THREAD

**Issue by dshanske** [pfefferle/wordpress-semantic-linkbacks#37]
I wanted to open the topic of storing additional data from the source URL as comment meta.

Things such as a summary, site name, language(it's in the pingback spec), featured image(if we can find one)... not sure what else might be relevant.

**Comment by pfefferle** [comment]
what do you think about saving the complete uf2 JSON object?

**Comment by dshanske** [comment]
That would work  except that would not be cross compatible with alternative parsers.

**Comment by dshanske** [comment]
I want to specifically explore storing syndication links for a post, child comments...

**Comment by dshanske** [comment]
Duplicate of #84
