### ISSUE TITLE
Optionally Automatically Approve Likes/Favorites/Reposts while Moderating Comments

### ISSUE THREAD

**Issue by dshanske** [pfefferle/wordpress-semantic-linkbacks#38]
The question is is this a desirable default behavior?

**Comment by dshanske** [comment]
There is a setting, "Comment author must have a previously approved comment."  What if it is the combination of a previously approved liked/favorite/repost that would create the approved list?

**Comment by armingrewe** [comment]
I would say previously approved like/favourite/repeat is a requirement for automatic approvals. I've had "spam accounts" favourite some of my tweets, wouldn't want these automatically approved. I would be happy to have friends who regularly like/favourite/repost to be automatically approved as that would save me time and work.

**Comment by dshanske** [comment]
Well, that raises another question. Bridgy webmentions all come from the same place, technically.
