### ISSUE TITLE
Rerun on Update

### ISSUE THREAD

**Issue by dshanske** [pfefferle/wordpress-semantic-linkbacks#39]
Linkback Fix should be rerun on update comment by being added to the edit comment hook.

**Comment by singpolyma** [comment]
I'm not sure if this is true, because of manually editing comments, etc.

related: https://github.com/pfefferle/wordpress-webmention/issues/57

**Comment by dshanske** [comment]
Maybe the solution is that updating a webmention has a hook to it that can rerun the function.

**Comment by pfefferle** [comment]
OK, found the problem... It is a result of this change: https://github.com/pfefferle/wordpress-semantic-linkbacks/commit/bb13b0ead73d7a299725af59827617f55913b13c

Not sure what the best fix would be atm. Reverting to the old `<linkback>_post` will break the notification mails and adding an `edit_comment` might result in an infinite loop or (as @singpolyma mentioned) will disallow manual changes.

**Comment by dshanske** [comment]
Well, currently only webmentions support update. So, adding the hook back to the webmention hook might work. All you have to do is add a flag very early on in linkback_fix that stops it if it finds the comment meta you added in, indicating it has already been processed.

**Comment by pfefferle** [comment]
but what about the notification emails?

**Comment by singpolyma** [comment]
What was causing emails to not go out? Adding a hook on a nonstandard action shouldn't affect core actions at all...

**Comment by pfefferle** [comment]
This was the problem: https://github.com/pfefferle/wordpress-semantic-linkbacks/issues/25

**Comment by singpolyma** [comment]
#25 is about presentation filters, which do not need to be changed. The proposal is to *add* a hook to the webmention action, and keep everything else (including all current hooks) as-is.

**Comment by pfefferle** [comment]
Sorry for my short answers :)

@dshanske detected that the `<linkback>_post` hooks are fired after the notification mail was sent, so the text in the mail was very limited and not interpreted by the semantic-linkbacks plugin. So we changed that to the `comment_post` hook and now have problems with the updates. So I think we should revert the changes to use the old hooks https://github.com/pfefferle/wordpress-semantic-linkbacks/commit/bb13b0ead73d7a299725af59827617f55913b13c

And wait until the notification improvement was discussed by the WordPress guys: https://core.trac.wordpress.org/ticket/33587

**Comment by singpolyma** [comment]
So, the proposal here to to *keep* the comment_post hook and *add* the webmention hook along with logic to prevent duplicating effort when a webmention comes in the first time.

**Comment by dshanske** [comment]
@singpolyma Exactly

**Comment by dshanske** [comment]
The notification improvement was to make notifying a hook on comment_post. Which fires before linkback_post

**Comment by pfefferle** [comment]
I am not sure if this fixes the problem completely, because the plugin also supports Pingbacks and Trackbacks, not only WebMentions.

**Comment by singpolyma** [comment]
But only webmentions support being updated. The others ignore dupes

**Comment by dshanske** [comment]
Let me see if I can work up a pull request in the next few days.

**Comment by pfefferle** [comment]
@singpolyma but why not improve linkbacks and trackbacks?

@dshanske what do you plan to add?

**Comment by pfefferle** [comment]
I am not sure if it is a good style to only use `comment_post` because of the limitation of the notification hooks. So I would prefer to use the `<linkback>_post` hooks, because they are per definition the correct one, and to improve the notification mails with hooks.

**Comment by dshanske** [comment]
To really change trackbacks and pingbacks we'd need Core to support a common handler for the two. Thinking of proposing it, but no one seems interested in Linkbacks in general.

**Comment by dshanske** [comment]
@pfefferle You want to bundle a custom notification function in Semantic Linkbacks?

**Comment by dshanske** [comment]
@pfefferle I was going to try to further break down the code.

**Comment by snarfed** [comment]
yay thank you!

**Comment by dshanske** [comment]
I am working on a better solution for this in 4.5
