### ISSUE TITLE
Use url_to_postid instead of text comparison for in-reply-to

### ISSUE THREAD

**Issue by singpolyma** [pfefferle/wordpress-semantic-linkbacks#44]
Instead of checking that the in-reply-to links link to the exact permalink of the post the comment is on, I propose instead checking if the post_ID we get from url_to_postid on the in-reply-to link matches the local post_ID -- this would allow for more flexibility for the format of the link on the remote (eg, both ?p= and rewrite forms would work).

**Comment by pfefferle** [comment]
Nice idea!

**Comment by dshanske** [comment]
This is good, but might cause a fragment issue. Will look
