### ISSUE TITLE
Comment Walker/Built-in Comment Display

### ISSUE THREAD

**Issue by dshanske** [pfefferle/wordpress-semantic-linkbacks#46]
Include custom comment walker and linkback display functions in plugin package that can better display these enhancements.

**Comment by dshanske** [comment]
The idea being that a base version could either be called or modified by a user. That would make it either a usable feature or a guide to creating their own version.

**Comment by dshanske** [comment]
I wanted to record some notes. I am proposing a function that takes a comment object or array and generates a marked up face for a pile, or a full display. And a variety of ways to call it...so it could be integrated into a theme, a comment walker, a call back function, etc.

**Comment by dshanske** [comment]
@pfefferle The preliminary setup is in https://github.com/dshanske/wordpress-semantic-linkbacks/tree/templates . Can you have a look and advise thoughts?

**Comment by pfefferle** [comment]
I think we implemented this now!
