### ISSUE TITLE
Formatting likes as mentions on new install

### ISSUE THREAD

**Issue by singpolyma** [pfefferle/wordpress-semantic-linkbacks#54]
See http://weber.teamchad.org/2015/12/christmas-greetings-and-thanks/#comment-6920 and https://brid.gy/log?start_time=1450900642&key=aglzfmJyaWQtZ3lySwsSCFJlc3BvbnNlIj10YWc6dHdpdHRlci5jb20sMjAxMzo2Nzk3NDg2Mjg2MTc5MDAwMzJfZmF2b3JpdGVkX2J5XzE2Njg1MDE1DA

**Comment by dshanske** [comment]
@singpolyma Is this still an issue?

**Comment by singpolyma** [comment]
I'll reopen if I see it again
