### ISSUE TITLE
Make It Easier to Keep PHP-MF2 updated

### ISSUE THREAD

**Issue by dshanske** [pfefferle/wordpress-semantic-linkbacks#58]
Originally suggested a Git Submodule to allow easy updating of the parser.

**Comment by pfefferle** [comment]
this does not work very well, I would prefer using composer.

**Comment by dshanske** [comment]
Either way, I want to make it easier to update php-mf2 as part of this plugin.

**Comment by pfefferle** [comment]
:thumbsup:
