### ISSUE TITLE
Reacji

### ISSUE THREAD

**Issue by dshanske** [pfefferle/wordpress-semantic-linkbacks#60]
https://indieweb.org/reacji#How_to

Bridgy is now displaying Facebook Reactions. Since they are coded as in-reply-to, the plugin displays them as a reply, which means comment form. I'd rather have them remain as webmention types, and allow them to be grouped together.

**Comment by dshanske** [comment]
https://github.com/dissolve/single-emoji-recognizer

Seems easy enough to use this to implement.

**Comment by dshanske** [comment]
@aaronpk also has a new library

**Comment by aaronpk** [comment]
https://github.com/aaronpk/emoji-detector-php

**Comment by miklb** [comment]
I'm looking to pick this up and wanted to know if it would be more appropriate in Semantic Linkbacks or a standalone plugin. I'm hoping to work on this during IWS.

**Comment by snarfed** [comment]
hey @miklb @dshanske did either of you get anywhere with this? is it easy to include an external library in a wordpress plugin? do you just bundle the source, or is there a more elegant way?

example post that would benefit from this:
https://snarfed.org/2017-10-31_25851
<img width="246" alt="image" src="https://user-images.githubusercontent.com/778068/32685165-c77f54f6-c640-11e7-8b12-194b7acd1e3a.png">

**Comment by miklb** [comment]
@snarfed no, it's still on my todo list. Yes, it's pretty straight forward to include a library. Seems like @aaronpk's would be a place to start. Where to hook it into the IndieWeb WordPress plugin ecosystem I'm not sure about and maybe why I've hesitated to tackle it.
