### ISSUE TITLE
Switch to Using php-comment

### ISSUE THREAD

**Issue by dshanske** [pfefferle/wordpress-semantic-linkbacks#61]
To make it easier to develop and improve, suggesting we switch over to php-comment to allow for wider development of features. 

https://github.com/indieweb/php-comments

**Comment by dshanske** [comment]
The only concern is the same concern over new versions of php-mf2 which is that we need to simplify updating the version. But it would mean that new features and improvements can be included outside the plugin.

**Comment by dshanske** [comment]
aaronpk is moving to xray as a replacement for php-comment. So will close this as development is shifting.

**Comment by pfefferle** [comment]
What is xray?

**Comment by dshanske** [comment]
https://github.com/aaronpk/XRay
