### ISSUE TITLE
unhappy with unicode content (e.g. reacji)

### ISSUE THREAD

**Issue by snarfed** [pfefferle/wordpress-semantic-linkbacks#71]
unicode chars in content like reacji have worked for me before, e.g. https://snarfed.org/2016-08-27_18491#comment-2600432 , but they're now rendered as _This Article was mentioned on brid-gy.appspot.com_, e.g. https://snarfed.org/2016-11-09_22762#comment-2601735 .

i've tried a few different versions, including current stable release and git head here.

i've tracked it down to [this `wp_update_comment` call](https://github.com/pfefferle/wordpress-semantic-linkbacks/blob/794a10db8c1aa5ade620edfc7974da512d47e272/includes/class-linkbacks-handler.php#L153). `$commentdata['comment_content']` has the right unicode content, e.g. 😢, but the `wp_update_comment` call returns 0 instead of 1, [which the docs say means it failed.](https://codex.wordpress.org/Function_Reference/wp_update_comment#Return_Values)

i can post comments manually with that same character, and they render ok, so i don't think it's wordpress's or mysql's fault. i've reproduced on wordpress 4.6.1 on both freebsd (mysql 14.14 5.6.23) and mac os x (mysql 14.14 5.7.14).

thanks in advance!

**Comment by pfefferle** [comment]
I think this was a problem with the latest changes in the web mention plugin... can you re-try it?

**Comment by snarfed** [comment]
thanks for the quick fix! webmentions now 404 for me...but evidently they did before this change too. not sure why. still investigating.

**Comment by pfefferle** [comment]
do you test on localhost? I readded the wp_safe_remote_* functions that does not support localhost. to test it in a local env you have to enable WP_DEBUG!

**Comment by snarfed** [comment]
thanks for checking. i get the 404s right now on both a real site (snarfed.org) and on localhost with DEBUG true.

**Comment by pfefferle** [comment]
do you get the 404 for the endpoint or the pinged/pinging urls?

**Comment by snarfed** [comment]
it's the webmention POSTs to the endpoint that fail. the target page itself 200s ok.

**Comment by pfefferle** [comment]
try to hit save on the permalinks page, so that the api links will be rebuild...

**Comment by dshanske** [comment]
Doesn't Bridgy cache endpoints? The endpoint moved in the new development version.

**Comment by snarfed** [comment]
ooh `/wp-json/webmention/1.0/endpoint`! thanks guys, yup, that was it.

webmentions do work now, but the reacji still render wrong, as _This Article was mentioned on brid-gy.appspot.com_ instead of e.g. 😢 . same example: https://snarfed.org/2016-11-09_22762#comment-2601753

i checked, and it's the same problem as originally described, `wp_update_comment` isn't returning 1, which means it's failing for some reason.

**Comment by snarfed** [comment]
(btw this happens both when updating an existing wm and when creating a new one, e.g. if i delete the existing one first, so it makes sense that pfefferle/wordpress-webmention@3115238 didn't fix it.)

**Comment by pfefferle** [comment]
This is a message added by the WM plugin, so the SL plugin is not loaded at all... I tested it with @voxpelli s [testpinger](https://github.com/voxpelli/node-webmention-testpinger) without problems...

**Comment by snarfed** [comment]
@pfefferle the semantic linkbacks plugin is definitely running. please reread the original issue description. :P i've added logging code to it, and it shows that it's running through `Linkbacks_MF2_Handler::generate_commentdata` and `Linkback_Handler::linkback_fix` and the call to `wp_update_comment()`, and that call returns null, which means it failed (i don't know why yet), and that failure is silently ignored.

**Comment by dshanske** [comment]
Look at this... https://core.trac.wordpress.org/ticket/38700

**Comment by snarfed** [comment]
@dshanske pretty sure that's unrelated. these comments aren't empty, and these plugins don't use the REST API.

**Comment by dshanske** [comment]
I was referring to the discussion about how wp_update_comment doesn't return useful errors.

**Comment by dshanske** [comment]
Also, it notes 0 could mean nothing is updated, which would mean we're passing in bad parameters.

**Comment by pfefferle** [comment]
I have no problems with new mentions, but updates seems to fail.

insert (WM) -> update (SL) :+1: 
update (WM) -> update (SL) :-1:

**Comment by dshanske** [comment]
@pfefferle How do you do your testing?

**Comment by pfefferle** [comment]
with a docker environment... see the docker-compose file in the webmention repo

**Comment by dshanske** [comment]
I meant how are you simulating an update?

**Comment by pfefferle** [comment]
Ah ok, I use the node-webmention-testpinger of @voxpelli to simulate updates, I start it several times ;)

**Comment by pfefferle** [comment]
this is btw. also possible in the docker env... see the testpinger instance...

**Comment by pfefferle** [comment]
with the latest changes of both plugins, it seems to work for me!

**Comment by pfefferle** [comment]
@snarfed @dshanske can you please verify?

**Comment by snarfed** [comment]
sorry, still unhappy. snarfed.org is at head in both this repo and https://github.com/pfefferle/wordpress-webmention . i tried resending your recent FB reaction https://brid.gy/facebook/212038#responses both as a new wm and an update. both get rendered as _This Article was mentioned on brid-gy.appspot.com_: https://snarfed.org/2016-11-09_22762#comment-2601772

**Comment by snarfed** [comment]
(the key point is that it's a reacji, ie has a non-ASCII unicode character. reply webmentions with plain ASCII text are rendered ok.)

**Comment by dshanske** [comment]
Could we be sanitizing the reacji? Also, should we be handling emojis differently? @dissolve has a single emoji detection function in his repositories I think.

**Comment by snarfed** [comment]
> Also, should we be handling emojis differently?

maybe! sounds beyond the scope of this bug though. the next step here is almost certainly to figure out why `wp_update_comment()` is failing in this case.

**Comment by dissolve** [comment]
I do, https://github.com/dissolve/single-emoji-recognizer

**Comment by dshanske** [comment]
I was just hoping in the course of focusing on them, the answer might become evident.

**Comment by pfefferle** [comment]
Tested it on my local env with this file and it works like @snarfed expected it...

**Comment by pfefferle** [comment]
I tested insert and updated...

**Comment by pfefferle** [comment]
My test file: https://github.com/pfefferle/node-webmention-testpinger/blob/bridgy-emoji-sample/templates/brid-gy-emoji.html

**Comment by snarfed** [comment]
thanks for testing @pfefferle! hrm. so then i need to figure out why it's failing in both of my environments.

any tips on debugging why `wp_update_comment()` is failing? @dshanske's earlier link to https://core.trac.wordpress.org/ticket/38700 is indeed a great explanation of how its error handling is insufficient, but doesn't say much on what to do about it right now.

**Comment by pfefferle** [comment]
Perhaps it is a combination of two plugins? have you tested it only with the WM and SL plugins on your local machine?

**Comment by snarfed** [comment]
ugh, you're absolutely right. i disabled all other plugins, and indeed, it works. second issue i've filed recently that's turned out to be due to my environment. sorry for the false alarm, and thank you so much for the help debugging!

i'll post more details when i've figured out the root cause.

**Comment by snarfed** [comment]
i re-enabled all of my plugins on localhost, one by one, testing between, and now it still works ok with all plugins enabled. argh! makes no sense.

guess i'll try the same thing on snarfed.org now.

**Comment by snarfed** [comment]
disabled plugins and switched to default theme on snarfed.org, but still doesn't work. argh indeed. :/

i'll keep investigating.

**Comment by pfefferle** [comment]
hmmm that's weird!

**Comment by snarfed** [comment]
aaaand it now works fine on a new post, without any new changes on my part. silly. :P

https://snarfed.org/2016-11-25_22841#comment-2601880

**Comment by pfefferle** [comment]
can we close this for now?

;)

**Comment by snarfed** [comment]
sure, sgtm.

**Comment by snarfed** [comment]
this is still happening to me sometimes. :/ e.g. the heart emoji replies came through fine here:

https://snarfed.org/2017-07-10_24721#li-comment-2605113

...but this face-with-sunglasses emoji didn't:

https://brid-gy.appspot.com/comment/instagram/snarfed/1561055543065208565_420973239/17874942562081351
on: https://snarfed.org/2017-07-17_24802#li-comment-2605378
