### ISSUE TITLE
Add ability to edit Linkbacks type and fields manually

### ISSUE THREAD

**Issue by dshanske** [pfefferle/wordpress-semantic-linkbacks#75]
Add these fields to the edit comment form in the admin. Partially this is also to allow viewing of this data in the admin.

**Comment by dshanske** [comment]
I was thinking of it being extra fields in edit comments to address this

**Comment by dshanske** [comment]
As for editing type, might be easier if we migrated to comment type for that.

**Comment by pfefferle** [comment]
@chrisaldrich I added the comment type in one of the latest Webmention versions (it shows at least if it is a comment or a Webmention)

**Comment by pfefferle** [comment]
@dshanske I like the idea, but we have to get sure that an update ping would not re-overwrite the manual changes!

**Comment by dshanske** [comment]
A checkbox to disable updates for that comment

**Comment by pfefferle** [comment]
Also not perfect, because then we also don‘t get text updates...

**Comment by dshanske** [comment]
Well, I'll start with editing and then figure out how to cope with updates.

**Comment by dshanske** [comment]
This has been resolved, I believe, except for overwriting the information on update.
