### ISSUE TITLE
Support for bookmark linkback type

### ISSUE THREAD

**Issue by chrisaldrich** [pfefferle/wordpress-semantic-linkbacks#77]
Tangentially related to https://github.com/pfefferle/wordpress-semantic-linkbacks/issues/75, but it appears that "mention", "like", and "reply" are supported natively, but not "bookmark"?

So for example, the comment display will default to X "mentioned" post  or Y "liked" post on service z, But would/could it say X "bookmarked" this post, particularly if the originating post had u-bookmark-of? I would presume that it would potentially have semantic_linkbacks_type be "bookmark" rather than "mention" or "reply" perhaps? And then that this could potentially be edited if the sending post wasn't carrying the correct mf2 class?

Example: http://boffosocko.com/2017/01/27/my-reply-to-micro-blog-project-surges-past-65k-on-kickstarter-gains-backing-from-dreamhost-wordpress-tavern/#comment-33624 which is a bookmark of the post technically rather than a simple mention, so it would be nice if it output "X bookmarked this post" in the comments in a parallel way as mentions and likes.

**Comment by pfefferle** [comment]
The plugin is supporting bookmarks in general, but not the version @aaronpk is publishing them. Is there a list of best practices?

**Comment by dshanske** [comment]
Well, aaronpk documents his implementation pretty well.

**Comment by dshanske** [comment]
I checked. My branch identifies this correctly.

**Comment by dshanske** [comment]
Should be addressed by #85

**Comment by dshanske** [comment]
This can be closed now.
