### ISSUE TITLE
Replace webmention verification functionality

### ISSUE THREAD

**Issue by dshanske** [pfefferle/wordpress-semantic-linkbacks#83]
Right now, the Webmention plugin verifies the Webmention and then the Semantic Linkbacks plugin evaluates it again. For webmentions, it could be modified so the Webmention plugin verification functionality is removed and a new function that verifies and enhances based on mf2 replaces it.

**Comment by pfefferle** [comment]
I would not remove, but extend it... I am currently thinking about fixing the OStatus stuff and I have a similar problem with the salmon comments. I think the best is to make the check filterable, so that the webmention plugin searches for different fields...

**Comment by dshanske** [comment]
That would work with my thoughts

**Comment by pfefferle** [comment]
cool!

**Comment by pfefferle** [comment]
is this still a problem?

**Comment by dshanske** [comment]
It was more of an enhancement. Let me look.
