### ISSUE TITLE
Date displayed as December 31, 1969

### ISSUE THREAD

**Issue by unrelentingtech** [pfefferle/wordpress-semantic-linkbacks#87]
I have posted [a reply](https://unrelenting.technology/replies/2017-05-16-15-06-01) to [a WordPress post](https://mmmicro.eli.li/2017/05/16/220/) on a site with IndieWeb Plugins. (GWG on #indieweb-dev suggested Semantic Linkbacks is responsible for this.)

My reply included this markup:
```html
<time class="dt-published" datetime="2017-05-16T15:06:01.133934073Z">
<a class="u-url u-uid note-permalink" rel="bookmark" href="/replies/2017-05-16-15-06-01">Tuesday, May 16th 2017, 15:06</a>
</time>
```

which is recognized by several mf2 parsers as
```json
"published": [
  "2017-05-16T15:06:01.133934073Z"
],
```

The date is valid ISO 8601 / RFC 3339.

And it's displayed as "December 31, 1969".

**Comment by dshanske** [comment]
I believe the issue is the microseconds. Might be better to switch to DateTime and add some error checking for formats.

**Comment by dshanske** [comment]
Not easily fixed, but the current PR will fail more logically

**Comment by dshanske** [comment]
I am back looking at this. Do you know what version of PHP you were running? I just tested this against several versions and only 5.2 returned null, or 1969.

**Comment by myfreeweb** [comment]
I'm not running PHP, I saw the error in another person's site that parsed my reply.
