### ISSUE TITLE
Pingbacks/Trackbacks Should Match Presentation of Webmentions

### ISSUE THREAD

**Issue by dshanske** [pfefferle/wordpress-semantic-linkbacks#9]
Inspired by Indieweb chat comment...
http://indiewebcamp.com/irc/2014-11-06/line/1415329191652

The Webmention plugin already intercepts trackbacks/pingbacks to appear identically to webmentions. 

An option should be added to convert existing pingbacks/trackbacks already in the database. This would allow for backward compatibility.

**Comment by snarfed** [comment]
+1!

**Comment by pfefferle** [comment]
I thought about implementing this as kind of an importer

**Comment by dshanske** [comment]
I have changed my view on this matter and now believe that the focus should be on Webmentions as the negative view of the older protocols is just too hard to overcome.
