### ISSUE TITLE
WordPress the_content and parsing

### ISSUE THREAD

**Issue by dshanske** [pfefferle/wordpress-semantic-linkbacks#92]
https://github.com/dshanske/indieweb-post-kinds/issues/99

This isn't strictly a Semantic Linkbacks issue, but being as all sorts of WordPress plugins add their markup to the_content, which is often wrapped by the theme in entry-content or e-content...how do we avoid this situation...as we can't adjust every theme in the repository? This is an issue in this plugin specifically because we want WordPress blogs to seamlessly use it.

**Comment by pfefferle** [comment]
I am not sure if this should/can be handled by the semantic link backs plugin. UF2 parsing is hard enough, I don't think we will be able to "fix" broken markups, because we never can be sure if something is intended or not. Do you have an idea?
