### ISSUE TITLE
Avatar should not be shown if mention has a user_id

### ISSUE THREAD

**Issue by dshanske** [pfefferle/wordpress-semantic-linkbacks#96]
The code that overrides the avatar with the stored URL should not do so if user_id is set.

**Comment by dshanske** [comment]
Add to this the discussed suggestion or searching for matches in the user profile.

**Comment by pfefferle** [comment]
this is very risky because it could be faked very easily

**Comment by dshanske** [comment]
This is already resolved. A set user id will override the retrieved Avatar. I agree at the moment that it shouldn't set it
